version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: callcountdb
    ports:
      - "5432:5432"
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
